In [1]:
def isprime(a):
    fc = fac_count(a)

In [2]:
def prime_range(lb,ub):
    for i in range(1,ub+1)
        if isprime(i):
            print(i)

SyntaxError: invalid syntax (<ipython-input-2-e4b278a17a4d>, line 2)

In [1]:
def prime(n):
    if n>2:
        print("not a prime")
    for i in range(2,n//2):
        if n%i==0:
             return false
        return true  
       if primes(46):
        print("is prime")
    else:
        print("not prime")
    
    list(filter(isdigit,li))
    
 


    

In [9]:
def addition(n):
    return n+n
addition(10)



20

In [4]:
list(map(addition,[4,7,8,2,10]))

[8, 14, 16, 4, 20]

In [10]:
def power(n):
    return n ** n

In [18]:
list(map(power,[11,9,7,1,0]))

[285311670611, 387420489, 823543, 1, 1]

def mul(n):

In [4]:
def sqrt(n):
    return n*n
list(map(sqrt,[1,2,3,4,56,]))
for i in 1:
    print(i)

TypeError: 'int' object is not iterable

[1 2 3 4 5 6 7 8 9]
prime 
even
odd

In [20]:
li = [1,2,'a','b','c',3]
def isdigit(n):
    n = str(n)
    if n.isdigit():
     return True
    return False

list(filter(isdigit,li))

[1, 2, 3]

In [21]:
 a1 = list(map(lambda x,y:(x+y)//2,m1,m2))
    print(a1)

IndentationError: unexpected indent (<ipython-input-21-9110a2b8508e>, line 2)

In [22]:
list(map(f,ite))
list(filter(f,tte))

NameError: name 'f' is not defined

In [23]:
list(filter(lambda x:x<10,a1))

NameError: name 'a1' is not defined

In [ ]:
numpy

In [34]:
import numpy as np

In [36]:
l = [1,2,3,4,5]
a1 = np.array(l)
print(a1)

[1 2 3 4 5]


In [37]:
l = [1,2,3,4,5]
a1 = np.array(1)
print(a1)

1


In [40]:
l2 = [[1,2,3],[4,5,6],[7,8,9]]
a2 = np.array(l2)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
a = np.arange(100).reshape(5,20)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [46]:
b = np.arange(20,26).reshape(2,3)
print(b)

[[20 21 22]
 [23 24 25]]
